//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScormPackager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScormPackager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- filename=adlcp_rootv1p2.xsd --&gt;
        ///&lt;!-- Conforms to w3c http://www.w3.org/TR/xmlschema-1/ 2000-10-24--&gt;
        ///
        ///&lt;xsd:schema xmlns=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot;
        ///            targetNamespace=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot;
        ///            xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;
        ///            xmlns:imscp=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot;
        ///            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///            elementFormDefault=&quot;unqualified&quot;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string adlcp_rootv1p2 {
            get {
                return ResourceManager.GetString("adlcp_rootv1p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;!-- filename=ims_xml.xsd --&gt;&lt;xsd:schema xmlns=&quot;http://www.w3.org/XML/1998/namespace&quot;             targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot;             xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;             elementFormDefault=&quot;qualified&quot;&gt;	&lt;!-- 2001-02-22 edited by Thomas Wason IMS Global Learning Consortium, Inc. --&gt;	&lt;xsd:annotation&gt;		&lt;xsd:documentation&gt;In namespace-aware XML processors, the &amp;quot;xml&amp;quot; prefix is bound to the namespace name http://www [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ims_xml {
            get {
                return ResourceManager.GetString("ims_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Thomas Wason (private) --&gt;
        ///&lt;!-- filename=ims_cp_rootv1p1p2.xsd --&gt;
        ///&lt;!-- Copyright (2) 2001 IMS Global Learning Consortium, Inc. --&gt;
        ///&lt;!-- edited by Thomas Wason  --&gt;
        ///&lt;!-- Conforms to w3c http://www.w3.org/TR/xmlschema-1/ 2000-10-24--&gt;
        ///
        ///&lt;xsd:schema xmlns=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot; 
        ///            targetNamespace=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot; 
        ///            xmlns:xml=&quot;http://www.w3.org/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string imscp_rootv1p1p2 {
            get {
                return ResourceManager.GetString("imscp_rootv1p1p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;manifest identifier=&quot;com.scorm.manifesttemplates.scorm12&quot; version=&quot;1&quot;
        ///       xmlns=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2&quot;
        ///       xmlns:adlcp=&quot;http://www.adlnet.org/xsd/adlcp_rootv1p2&quot;
        ///       xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///       xsi:schemaLocation=&quot;http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
        ///                           http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
        ///                           http://www [rest of string was truncated]&quot;;.
        /// </summary>
        public static string imsmanifest {
            get {
                return ResourceManager.GetString("imsmanifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited by Thomas Wason  --&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1&quot; 
        ///            xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; 
        ///            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///            xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///            xmlns=&quot;http://www.imsglobal.org/xsd/imsmd_rootv1p2p1&quot; 
        ///            elementFormDefault=&quot;qualified&quot; 
        ///            version=&quot;1.2:1.1 IMS:MD1.2&quot;&gt;
        ///
        ///   &lt;xsd:impor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string imsmd_rootv1p2p1 {
            get {
                return ResourceManager.GetString("imsmd_rootv1p2p1", resourceCulture);
            }
        }
    }
}
